export const disciplinas = [
    {
        id: 'algoritmos',
        titulo: 'Algorítmos',
        area: 'exatas',
        professor: 'Jorge Farias',
        descricao: 'Uma disciplina daora',
    },
    {
        id: 'logica',
        titulo: 'Logica e Matemática Discreta',
        area: 'exatas',
        professor: 'Maria Lívia',
        descricao: 'Uma disciplina bacana',
    },
    {
        id: 'comunicacao',
        titulo: 'Comunicação e Expressão',
        area: 'humanas',
        professor: 'Maria Constância',
        descricao: 'Uma disciplina massa',
    },
    {
        id: 'ingles',
        titulo: 'Inglês Instrumental',
        area: 'humanas',
        professor: 'Edvan Silva',
        descricao: 'Uma disciplina bacana',
    },
    {
        id: 'sociologia',
        titulo: 'Sociologia',
        area: 'humanas',
        professor: 'Cláudio Amorim',
        descricao: 'Uma disciplina bacana',
    },
    {
        id: 'fundamentos',
        titulo: 'Fundamentos da Informática',
        area: 'exatas',
        professor: 'Antônio Atta',
        descricao: 'Uma disciplina bacana',
    },
    {
        id: 'bioinformatica',
        titulo: 'Bioinformática',
        area: 'biologicas',
        professor: 'Lenz',
        descricao: 'Uma disciplina bacana',
    },
];
